---
  - name: "make sure to use project {{ SBR_APPLICATION_NAMESPACE }}"
    command: "oc project {{ SBR_APPLICATION_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: false
    
  - name: importing required Prometheus ImageStreamTags from upstream Registries
    command: "oc tag --namespace {{ SBR_INFRA_NAMESPACE }} prom/pushgateway:latest prom/pushgateway:latest"

  - name: create Prometheus pushgateway deployment, and service
    command: oc new-app --docker-image=prom/pushgateway --name=pushgateway
    ignore_errors: true
    changed_when: false

  - name: Expose the route
    command: oc expose svc/pushgatewayk
    ignore_errors: true
    changed_when: false
