---
  - name: "make sure to use project {{ SBR_APPLICATION_NAMESPACE }}"
    command: "oc project {{ SBR_APPLICATION_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: "check if ImageStream exists"
    command: "oc get imagestream --namespace {{ SBR_APPLICATION_NAMESPACE }} sbr-job"
    register: imagestream_exists
    ignore_errors: true
    changed_when: False

  - name: create sbr ImageStream
    command: oc new-app --namespace "{{ SBR_APPLICATION_NAMESPACE }}" --template="{{ SBR_INFRA_NAMESPACE }}/sbr-imagestream"
    when: imagestream_exists is failed
    
  - name: "check if BuildConfig exists"
    command: "oc get buildconfig --namespace {{ SBR_APPLICATION_NAMESPACE }} sbr-job"
    register: buildconfig_exists
    ignore_errors: true
    changed_when: False

  - name: create sbr BuildConfig
    command: oc new-app --namespace "{{ SBR_APPLICATION_NAMESPACE }}" --template="{{ SBR_INFRA_NAMESPACE }}/sbr-buildconfig"
    when: buildconfig_exists is failed

  - name: start sbr-job Build
    command: oc start-build --namespace "{{ SBR_APPLICATION_NAMESPACE }}" sbr-job
    when: buildconfig_exists is failed
